const alasql = require('alasql');

function executePlan(data, plan) {
  try {
    // plan.sql is the SQL query generated by the LLM, e.g. "SELECT Category, SUM(Sales) AS value FROM ? GROUP BY Category"
    // 'data' is your array of row objects from the Excel file, passed into the '?' placeholder
    return alasql(plan.sql, [data]);
  } catch (error) {
    console.error("SQL Execution Error:", error);
    return [];
  }
}

module.exports = executePlan;
